#+TITLE: Font Configuraitons
#+AUTHOR: oxcl
#+PROPERTY: header-args :tangle yes
* TLDR
This Emacs package configures custom fonts with fallbacks, using my modified Iosevka font. It defines monospace, sans-serif, and serif fontsets for different scripts. The setup improves font rendering performance, especially on Windows, by specifying language fonts.
* Description
This package configures emacs to use [[https://github.com/oxcl/iozevka][iozevka fonts]]. my modified version of the [[https://github.com/be5invis/iosevka][Iosevka font]].
multiple fallbacks are set to make sure alternative fonts are used in case iozevka fonts are not installed.

* Config
#+BEGIN_SRC elisp
  (use-package fonts
    :ensure nil
    :no-require
    :if (display-graphic-p)
    :demand t
    :config
#+END_SRC
** Helper Functions
#+BEGIN_SRC elisp
  (defun ox/create-fontset (name)
    "create an empty fontset named NAME"
    (create-fontset-from-fontset-spec
     (font-xlfd-name
      (font-spec :registry name))))

  (defun ox/set-default-font (&rest fonts)
    "set the default/main emacs font with fallbacks"
    (unless (null fonts)
      (if (find-font (font-spec :name (car fonts)))
	  (set-face-attribute 'default nil
			      :font (car fonts)
			      :height 90)
	(apply #'ox/set-default-font (cdr fonts)))))

  (defun ox/set-font (fontset script fonts)
    "set a font for a specific SCRIPT in FONTSET with fallbacks.
     if non of the fonts are available look for an appropriate font on the system"
    (set-fontset-font fontset script (car fonts))
    (dolist (font (cdr fonts))
      (set-fontset-font fontset script font nil 'append))
    (set-fontset-font fontset script (font-spec :script script) nil 'append))
#+END_SRC
** Proportional Fonts
this package provides two new fontsets: ~fontset-sans~ and ~fontset-serif~ which are proportional fonts that can be used with ~variable-pitch-mode~, ~mixed-pitch-mode~ and everywhere that a proportional font is more appropriate.

*** Sans Serif
The Sans Serif font is the main *proportional* font in my config. and it may be used anywhere where a monospace grid is not neccessary.
The Sans Serif fonts are also used as a fallback for the monospace and serif fonts so that in case non of the fonts for a specific script are available on the system at least the characters are displayed using a sans-serif font.
#+BEGIN_SRC elisp
  (ox/create-fontset "fontset-sans")
#+END_SRC
**** Latin
for Latin I use ~ioZevka Quasi~ which is the proportional variant of ~ioZevka Code~.This will ensure a consistent look across both monospace and proportional text inside emacs.
I also specify bunch of Fallbacks which are common in linux distrobutions and windows systems.
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-latin '("ioZevka Quasi"
			 "Noto Sans"
			 "Arimo"
			 "Liberation Sans"
			 "FreeSans"
			 "DejaVu Sans"
			 "Segoe UI"))
  (ox/set-font "fontset-sans" 'latin ox/fonts-fallback-latin)
#+END_SRC
**** Arabic/Farsi
for Arabic/Farsi I use [[https://github.com/rastikerdar/vazirmatn][Vazir Matn]] which is the proportional variant of ~Vazir Code~. I also specify [[https://fonts.google.com/noto/specimen/Noto+Sans+Arabic][Noto Sans Arabic]], [[https://fonts.google.com/noto/specimen/Noto+Naskh+Arabic][Noto Naskh Arabic]] and IRANSansWeb as fallbacks.
#+BEGIN_QUOTE
سلام چطوری؟
#+END_QUOTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-arabic '("Vazirmatn UI NL"
			       "Vazirmatn UI"
			       "Vazirmatn NL"
			       "Vazirmatn"
			       "Noto Sans Arabic"
			       "Noto Naskh Arabic"
			       "IRANSansWeb"
			       "Segoe UI")) ; for windows
  (ox/set-font "fontset-sans" 'arabic ox/fonts-fallback-arabic)
#+END_SRC

**** CJK
#+BEGIN_QOUTE
你好
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-han '("Noto Sans CJK SC"
				"MS Gothic")) ; for windows
  (ox/set-font "fontset-sans" 'han ox/fonts-fallback-han)
#+END_SRC
#+BEGIN_QOUTE
こんにちは
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-kana '("Noto Sans CJK JP"
				 "MS Gothic")) ; for windows
  (ox/set-font "fontset-sans" 'han ox/fonts-fallback-kana)
#+END_SRC
#+BEGIN_QOUTE
안녕하세요
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-hangul '("Noto Sans CJK KR"
				   "Malgun Gothic")) ; for windows
  (ox/set-font "fontset-sans" 'hangul ox/fonts-fallback-hangul)
#+END_SRC
**** Hebrew
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-hebrew '("Noto Sans Hebrew"))
  (ox/set-font "fontset-sans" 'hebrew ox/fonts-fallback-hebrew)
#+END_SRC
**** South East Asian Scripts
#+BEGIN_QOUTE
 ជំរាបសួរ
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-khmer '("Noto Sans Khmer"
				  "Leelawadee UI")) ; for windows
  (ox/set-font "fontset-sans" 'khmer ox/fonts-fallback-khmer)
#+END_SRC
#+BEGIN_QOUTE
ສະບາຍດີ
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-lao '("Noto Sans Lao"
				"Leelawadee UI")) ; for windows
  (ox/set-font "fontset-sans" 'lao ox/fonts-fallback-lao)
#+END_SRC
#+BEGIN_QOUTE
မင်္ဂလာပါ
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-burmese '("Noto Sans Myanmar"
				    "Myanmar Text")) ; for windows
  (ox/set-font "fontset-sans" 'burmese ox/fonts-fallback-burmese)
#+END_SRC
#+BEGIN_QOUTE
สวัสดีครับ
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-thai '("Noto Sans Thai"
				 "Leelawadee UI")) ; for windows
  (ox/set-font "fontset-sans" 'thai ox/fonts-fallback-thai)
#+END_SRC

**** Ethiopic
#+BEGIN_QOUTE
ሠላም
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-ethiopic '("Noto Sans Ethiopic"
				     "Ebrima")) ; for windows
  (ox/set-font "fontset-sans" 'ethiopic ox/fonts-fallback-ethiopic)
#+END_SRC

**** South Asian Scripts
#+BEGIN_QOUTE
નમસ્તે
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-gujarati '("Noto Sans Gujarati"
				     "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'gujarati ox/fonts-fallback-gujarati)
#+END_SRC
#+BEGIN_QOUTE
नमस्ते
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-devanagari '("Noto Sans Devanagari"
				      "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'devanagari ox/fonts-fallback-devanagari)
#+END_SRC
#+BEGIN_QOUTE
ನಮಸ್ಕಾರ
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-kannada '("Noto Sans Kannada"
				   "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'kannada ox/fonts-fallback-kannada)
#+END_SRC
#+BEGIN_QOUTE
നമസ്കാരം
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-malayalam '("Noto Sans Malayalam"
				      "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'malayalam ox/fonts-fallback-malayalam)
#+END_SRC
#+BEGIN_QOUTE
ଶୁଣିବେ
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-oriya '("Noto Sans Oriya"
				  "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'oriya ox/fonts-fallback-oriya)
#+END_SRC
#+BEGIN_QOUTE
ආයුබෝවන්
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-sinhala '("Noto Sans Sinhala"
				    "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'sinhala ox/fonts-fallback-sinhala)
#+END_SRC
#+BEGIN_QOUTE
வணக்கம்
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-tamil '("Noto Sans Tamil"
			      "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'tamil ox/fonts-fallback-tamil)
#+END_SRC
#+BEGIN_QOUTE
నమస్కారం
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-telugu '("Noto Sans Telugu"
			       "Nirmala UI")) ; for windows
  (ox/set-font "fontset-sans" 'telugu ox/fonts-fallback-telugu)
#+END_SRC
#+BEGIN_QOUTE
བཀྲ་ཤིས་བདེ་ལེགས༎
#+END_QOUTE
#+BEGIN_SRC elisp
  (setq ox/fonts-fallback-tibetan '("Noto Sans Tibetan"
				"Microsoft Himalaya")) ; for windows
  (ox/set-font "fontset-default" 'tibetan ox/fonts-fallback-tibetan)
#+END_SRC

**** Setup
#+BEGIN_SRC elisp
    (set-face-attribute 'variable-pitch nil
  		      :font "fontset-sans"
  		      :fontset "fontset-sans"
  		      :height 1.2)
#+END_SRC

*** Serif
For Serif fonts i mainly use iozevka slabs for latin and the ~Noto Serif Fonts~ and I use the sans-serif fonts as fallback in case serif fonts are not available on the system.
#+BEGIN_SRC elisp
  (ox/create-fontset "fontset-serif")
#+END_SRC
**** Latin
For Latin I use ~ioZevka Slabs~ which is the same as ~ioZevka Quasi~ but... with slabs.
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'latin
	       `("ioZevka Slabs"
		 "Noto Serif"
		 "Liberation Serif"
		 "FreeSerif"
		 "Dejavu Serif"
		 "Times New Roman" ; for windows
		 ,@ox/fonts-fallback-latin))
#+END_SRC

**** Arabic/Farsi
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'arabic
	       `("Noto Naskh Arabic"
		 "Arial" ; for windows
		 ,@ox/fonts-fallback-arabic))
#+END_SRC

**** CJK
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'han
	       `("Noto Serif CJK SC"
		 ,@ox/fonts-fallback-han))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'kana
	       `("Noto Serif CJK JP"
		 ,@ox/fonts-fallback-kana))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'hangul
	       `("Noto Serif CJK KP"
	       ,@ox/fonts-fallback-hangul))
#+END_SRC
**** Hebrew
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'hebrew
	       `("Noto Serif Hebrew"
		 ,@ox/fonts-fallback-hebrew))
#+END_SRC
**** South East Asian Scripts
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'khmer
	       `("Noto Serif Khmer"
		 ,@ox/fonts-fallback-khmer))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'lao
	       `("Noto Serif Lao"
		 ,@ox/fonts-fallback-lao))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'burmese
	       `("Noto Serif Myanmar"
		 ,@ox/fonts-fallback-burmese))
#+END_SRC
#+BEGIN_SRC elisp
      (ox/set-font "fontset-serif"
		   'thai
		   `("Noto Serif Thai"
		     ,@ox/fonts-fallback-thai))
#+END_SRC
**** Ethiopic
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'ethiopic
	       `("Noto Serif Ethiopic"
		 ,@ox/fonts-fallback-ethiopic))
#+END_SRC
**** South Asian Scripts
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'gujarati
	       `("Noto Serif Gujarati"
		 ,@ox/fonts-fallback-gujarati))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'devanagari
	       `("Noto Sans Devanagari"
		 ,@ox/fonts-fallback-devanagari))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'kannada
	       `("Noto Serif Kannada"
		 ,@ox/fonts-fallback-kannada))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'malayalam
	       `("Noto Serif Malayalam"
		 ,@ox/fonts-fallback-malayalam))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'oriya
	       `("Noto Serif Oriya"
		 ,@ox/fonts-fallback-oriya))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'sinhala
	       `("Noto Serif Sinhala"
		 ,@ox/fonts-fallback-sinhala))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'tamil
	       `("Noto Serif Tamil"
		 ,@ox/fonts-fallback-tamil))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'telugu
	       `("Noto Serif Telugu"
		 ,@ox/fonts-fallback-telugu))
#+END_SRC
#+BEGIN_SRC elisp
  (ox/set-font "fontset-serif"
	       'tibetan
	       `("Noto Sans Tibetan"
		 ,@ox/fonts-fallback-tibetan))
#+END_SRC

** Monospace
For monospace i modify the default font by changing the ~:font~ attribute of ~default~ face.
To make sure characters from other languages and alphabets won't break the monospace grid, specific monospace fonts for arabic, hebrew, chinese and korean are also added to the ~fontset-default~ fontset which emacs will fallback to if a character is not provided by the main font.
if no monospace font is available for a script or alphabet the sans serif fonts are used as a fallback.

*** Latin
I use ~ioZevka Code~ as my main font for latin scripts. ~ioZevka Mono~ is also set as fallback which is the same as ~ioZevka Code~ just without the ligatures.
If ~ioZevka Code~ is not available on the system i use [[https://github.com/JetBrains/JetBrainsMono][JetBrains Mono]] and [[https://fonts.google.com/noto/specimen/Noto+Sans+Mono][Noto Sans Mono]] as fallbacks.
#+BEGIN_SRC elisp
  (ox/set-default-font "ioZevka Code"
		       "ioZevka Mono"
		       "JetBrains Mono"
		       "Noto Sans Mono"
		       "Courier New" ; for windows
		       "monospace")
#+END_SRC
*** Arabic/Farsi
For Arabic/Farsi I use [[https://github.com/rastikerdar/vazir-code-font][Vazir Code Font]].
#+BEGIN_SRC elisp
  ;; سلام چطوری؟
  (ox/set-font "fontset-default"
	       'arabic
	       `(,(font-spec :name "Vazir Code Extra Height WOL" :size 13)
		 ,(font-spec :name "Vazir Code Extra Height" :size 13)
		 ,(font-spec :name "Vazir Code WOL" :size 13)
		 ,(font-spec :name "Vazir Code" :size 13)
		 "Courier New" ; for windows
		 "monospace"
		 ,@ox/fonts-fallback-arabic))
#+END_SRC

*** CJK
For CJK I use [[https://github.com/be5invis/Sarasa-Gothic][Sarasa Gothic]] and [[https://github.com/adobe-fonts/source-han-mono][Source Han Mono]] as fallback.
#+BEGIN_SRC elisp
  ;; 你好 早晨
  (ox/set-font "fontset-default"
	       'han
	       `("Sarasa Mono SC"
		 "Source Han Mono SC"
		 ,@ox/fonts-fallback-han))
  ;; こんにちは
  (ox/set-font "fontset-default"
	       'kana
	       `("Sarasa Mono J"
		 ,@ox/fonts-fallback-kana))
  ;; 안녕하세요
  (ox/set-font "fontset-default"
	       'hangul
	       `("Sarasa Mono K"
		 "Source Han Mono K"
		 ,@ox/fonts-fallback-hangul))
#+END_SRC

*** Hebrew
For Hebrew I use [[https://www.gnu.org/software/freefont/][FreeMono]].
#+BEGIN_SRC elisp
  ;; Hebrew:  חפש סתם אהב
  (ox/set-font "fontset-default"
	       'hebrew
	       '("FreeMono"
		 "Courier New"))
#+END_SRC
*** South East Asian Scripts
for these fonts i don't have a specific monospace font so i just use the sans-serif fallbacks
#+BEGIN_SRC elisp
  (ox/set-font "fontset-default" 'khmer   ox/fonts-fallback-khmer)
  (ox/set-font "fontset-default" 'lao     ox/fonts-fallback-lao)
  (ox/set-font "fontset-default" 'burmese ox/fonts-fallback-burmese)
  (ox/set-font "fontset-default" 'thai    ox/fonts-fallback-thai)
#+END_SRC
*** Ethiopic
#+BEGIN_SRC elisp
  (ox/set-font "fontset-default" 'ethiopic ox/fonts-fallback-ethiopic)
#+END_SRC
*** South Asian Scripts
#+BEGIN_SRC elisp
  (ox/set-font "fontset-default" 'gujarati  ox/fonts-fallback-gujarati)
  (ox/set-font "fontset-default" 'devanagari ox/fonts-fallback-devanagari)
  (ox/set-font "fontset-default" 'kannada   ox/fonts-fallback-kannada)
  (ox/set-font "fontset-default" 'malayalam ox/fonts-fallback-malayalam)
  (ox/set-font "fontset-default" 'oriya     ox/fonts-fallback-oriya)
  (ox/set-font "fontset-default" 'sinhala   ox/fonts-fallback-sinhala)
  (ox/set-font "fontset-default" 'tamil     ox/fonts-fallback-tamil)
  (ox/set-font "fontset-default" 'telugu    ox/fonts-fallback-telugu)
  (ox/set-font "fontset-default" 'tibetan   ox/fonts-fallback-tibetan)
#+END_SRC
*** Setup
#+BEGIN_SRC elisp
    (set-face-attribute 'fixed-pitch nil
		      :font "fontset-default"
		      :fontset "fontset-default")
#+END_SRC

** Emoji
#+BEGIN_QOUTE
❤️😎
#+END_QOUTE
#+BEGIN_SRC elisp
  (ox/set-font "fontset-default"
  	       'emoji
  	       '("Apple Color Emoji"
  		 "Noto Color Emoji"
  		 "Noto Emoji"))
  ;;emacs on windows does not support colored emojis
  (when (eq system-type 'windows-nt)
    (ox/set-font "fontset-default"
  		 'emoji
  		 '("Noto Emoji"
  		   "Segoe UI Emoji")))
#+END_SRC
** End
#+BEGIN_SRC elisp
  ) ; end of use-package
#+END_SRC
* Notes
** Note About Windows
on windows looking up for proper fonts specially for langauges and scripts other than english is extremly slow. by explicitly defining the fonts that windows uses for rendering those characters would significantly improves performance of emacs on windows.

** Note About Fontsets
A fontset is a collection of multiple fonts which each of them display a range of specific characters for an alphabet or scripts. emacs uses ~fontset-default~ as the fallback fontset so that if a character is not available on the font of a specific face the ~fontset-default~ fontset is utilized.
Because of this I really wanted to have 3 fontsets in my configuration:
 - ~fontset-mono~
 - ~fontset-sans~
 - ~fontset-serif~

the prolem with this is that the fontset implementation in emacs is buggy and underdocumented. so I was not able to ahieve this.
instead I used ~fontset-default~ as the main monospace fontset which will fallback to sans-serif fonts so that if non of the monospace fonts for a script are available on the system at least the characters are not shown as hex characters and boxes, which is redundant and not ideal but it is what it is.
